version: '3.4'

services:
  shopmanager:
    image: ${DOCKER_REGISTRY-}shopmanager
    hostname: shopmanager
    container_name: shopmanager
    restart: always
    build:
      context: .
      dockerfile: WebFront/ShopManager/Dockerfile

  shop.api:
    image: ${DOCKER_REGISTRY-}shopapi
    hostname: shopapi
    container_name: shopapi
    restart: always
    build:
      context: .
      dockerfile: Microservices/Shop/Shop.API/Dockerfile
    depends_on:
        - db
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    hostname: sqlserver
    container_name: sqlserver
    restart: always
    
